import { useEffect, useState } from "react";
import { IconCheck, IconEdit, IconFileText } from "@tabler/icons-react";
import { api, todayStr } from "../api.js";
import DateNav from "../components/DateNav.jsx";
import GenerateButton from "../components/GenerateButton.jsx";

export default function DailyReportPage(){
 const [date,setDate]=useState(todayStr());const [report,setReport]=useState(null);const [sources,setSources]=useState({total:0});const [busy,setBusy]=useState(false);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState("");
 const load=async()=>{const [daily,raw]=await Promise.all([api.get(`/reports/daily?date=${date}`),api.get(`/reports/dingtalk?date=${date}`)]);setReport(daily.report);setSources(raw)};useEffect(()=>{load()},[date]);
 const gen=async()=>{setBusy(true);try{await api.post("/reports/daily/generate",{date});await load()}finally{setBusy(false)}};const edit=()=>{setDraft(report?.content_json?.summary||"");setEditing(true)};const save=async()=>{setBusy(true);try{await api.put("/reports/daily",{date,content:{summary:draft}});await load();setEditing(false)}finally{setBusy(false)}};const c=report?.content_json||{};
 return <div><div className="panel" style={{marginBottom:14}}><div className="panel__head"><div className="panel__title"><IconFileText size={20}/>主管日报</div><DateNav date={date} onChange={setDate}/></div><p className="meta">本页只保留可编辑主管摘要；{sources.total} 名成员的原始日志请在「团队」工作区按成员下钻。</p></div><div className="panel"><div className="panel__head"><div className="panel__title">{date} 汇报摘要</div><div className="row"><GenerateButton onClick={gen} busy={busy} />{report&&!editing&&<button className="btn sm" onClick={edit}><IconEdit size={15}/>编辑</button>}{editing&&<button className="btn primary sm" onClick={save} disabled={busy}><IconCheck size={15}/>保存</button>}</div></div>{report?<div>{editing?<textarea value={draft} onChange={(e)=>setDraft(e.target.value)} rows={7} style={{width:"100%"}}/>:<p style={{fontSize:16,lineHeight:1.8}}>{typeof c.summary==="string"?c.summary:"（摘要格式异常，请重新生成）"}</p>}<div className="grid grid-2"><div><div className="sub">团队阻塞</div><ul>{(c.teamBlockers||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></div><div><div className="sub">需主管审核</div><ul>{(c.needManagerReview||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></div></div><div className="meta">来源 {c.sourceRefs?.length||0} 项 · 生成于 {c.generatedAt?new Date(c.generatedAt).toLocaleString("zh-CN"):report.generated_at}</div></div>:<div className="empty">该日期尚未生成主管日报。</div>}</div></div>;
}
