import { useEffect, useMemo, useState } from "react";
import { IconAlertTriangle, IconCheck, IconClock, IconExternalLink, IconPlus, IconRefresh, IconSearch, IconSend, IconX } from "@tabler/icons-react";
import { meetingsApi } from "../api.js";
import { PageHeader } from "../components/PageHeader.jsx";
import "./MeetingsPage.css";

const VIEWS = [["pending", "待处理"], ["processed", "已处理"], ["failed", "创建失败"]];
const KIND = { action: "行动项", decision: "需决策", risk: "风险/阻塞" };
function fmt(value) { return value ? new Date(value).toLocaleString("zh-CN", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "时间未知"; }

export default function MeetingsPage() {
  const [view, setView] = useState("pending"); const [meetings, setMeetings] = useState([]); const [active, setActive] = useState(null);
  const [reference, setReference] = useState(""); const [query, setQuery] = useState(""); const [matches, setMatches] = useState([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(null);
  const load = async (nextView = view) => { try { const result = await meetingsApi.list(nextView); setMeetings(result.items); if (active) { const current = await meetingsApi.detail(active.id); setActive(current.item); } } catch (e) { setError(e.message); } };
  useEffect(() => { void load(view); }, [view]);
  const selected = useMemo(() => (active?.items || []).filter((item) => ["draft", "selected", "failed"].includes(item.status)), [active]);
  const open = async (item) => { setPreview(null); try { setActive((await meetingsApi.detail(item.id)).item); } catch (e) { setError(e.message); } };
  const sync = async () => { setBusy(true); setError(""); try { await meetingsApi.sync(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const importMeeting = async (value = reference) => { setBusy(true); setError(""); try { const result = await meetingsApi.import(value); setReference(""); setMatches([]); setActive(result); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const search = async () => { if (!query.trim()) return; setBusy(true); setError(""); try { setMatches((await meetingsApi.search(query.trim())).items); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const patch = async (id, next) => { try { await meetingsApi.updateItem(id, next); setActive((await meetingsApi.detail(active.id)).item); await load(); } catch (e) { setError(e.message); } };
  const makePreview = async () => { try { setPreview(await meetingsApi.preview(active.id, selected.map((item) => item.id))); } catch (e) { setError(e.message); } };
  const confirm = async () => { setBusy(true); try { const result = await meetingsApi.confirm(active.id, preview.id); setActive(result.meeting); setPreview(null); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <div className="meetings-page"><PageHeader eyebrow="MEETINGS / FOLLOW-UP" title="会议闭环" description="从钉钉 AI 听记提取行动项、决策与风险，确认后创建钉钉待办。" />
    {error && <div className="error">{error}</div>}
    <section className="panel meeting-tools"><div className="meeting-tools__row"><button className="btn primary" onClick={sync} disabled={busy}><IconRefresh size={15} />同步近 7 天听记</button><div className="meeting-import"><input value={reference} onChange={(e) => setReference(e.target.value)} placeholder="粘贴含 taskUuid 的听记链接或 ID" /><button className="btn" disabled={busy || !reference.trim()} onClick={() => importMeeting()}><IconPlus size={15} />导入</button></div></div><div className="meeting-tools__row"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="按会议标题搜索听记" onKeyDown={(e) => e.key === "Enter" && search()} /><button className="btn sm" disabled={busy || !query.trim()} onClick={search}><IconSearch size={15} />搜索</button></div>{matches.length > 0 && <div className="meeting-matches">{matches.map((item) => <button key={item.minutesId} onClick={() => importMeeting(item.minutesId)}><span>{item.title}</span><small>{fmt(item.meetingAt)}</small></button>)}</div>}</section>
    <div className="meeting-tabs">{VIEWS.map(([key, label]) => <button key={key} className={view === key ? "active" : ""} onClick={() => { setView(key); setActive(null); }}>{label}</button>)}</div>
    <div className="meeting-layout"><section className="meeting-list panel">{meetings.length ? meetings.map((item) => <button className={`meeting-list__item ${active?.id === item.id ? "active" : ""}`} onClick={() => open(item)} key={item.id}><span className={`meeting-status meeting-status--${item.status}`}>{item.status === "pending" ? "待处理" : item.status === "failed" ? "失败" : "已处理"}</span><strong>{item.title}</strong><small>{fmt(item.meeting_at)} · {item.open_count || 0} 项待办</small></button>) : <div className="empty">暂无{VIEWS.find((v) => v[0] === view)?.[1]}会议</div>}</section>
      <section className="meeting-detail panel">{!active ? <div className="empty"><IconClock size={22} />从左侧选择会议，或同步/导入一条钉钉听记。</div> : <><header className="meeting-detail__head"><div><div className="panel__title">{active.title}</div><div className="meta">{fmt(active.meeting_at)}{active.organizer ? ` · ${active.organizer}` : ""}</div></div>{active.source_url && <a className="btn sm" href={active.source_url} target="_blank" rel="noreferrer">打开听记 <IconExternalLink size={14} /></a>}</header><p className="meeting-summary">{active.summary || "钉钉听记尚未生成摘要。"}</p>{active.keywords?.length > 0 && <div className="meeting-keywords">{active.keywords.map((word) => <span key={word}>{word}</span>)}</div>}<div className="meeting-ai-note">{active.aiMeta ? "已使用当前工作台 AI 补充决策与风险。" : "未进行增强分析；保留钉钉 AI 听记原始行动项。"}</div><div className="meeting-items">{active.items.map((item) => <article className={`meeting-item meeting-item--${item.kind}`} key={item.id}><div className="meeting-item__kind">{item.kind === "risk" ? <IconAlertTriangle size={16} /> : item.kind === "action" ? <IconCheck size={16} /> : <IconClock size={16} />}{KIND[item.kind]}</div><input className="meeting-item__title" value={item.title} disabled={item.status === "created"} onChange={(e) => patch(item.id, { title: e.target.value })} /><div className="meeting-item__fields"><input placeholder="负责人（DWS 用户 ID）" value={item.assignee_id || ""} disabled={item.status === "created"} onChange={(e) => patch(item.id, { assigneeId: e.target.value || null })} /><input type="date" value={item.due_date || ""} disabled={item.status === "created"} onChange={(e) => patch(item.id, { dueDate: e.target.value || null })} /><select value={item.priority} disabled={item.status === "created"} onChange={(e) => patch(item.id, { priority: e.target.value })}><option value="P0">P0</option><option value="P1">P1</option><option value="P2">P2</option></select></div><textarea placeholder="备注" value={item.note || ""} disabled={item.status === "created"} onChange={(e) => patch(item.id, { note: e.target.value })} /> <div className="meeting-item__foot">{item.status === "created" ? <span className="pill green">已创建 · {item.external_task_id}</span> : item.status === "failed" ? <span className="pill red">创建失败，可重新选择</span> : <><button className={`btn sm ${item.status === "selected" ? "primary" : ""}`} onClick={() => patch(item.id, { status: item.status === "selected" ? "draft" : "selected" })}>{item.status === "selected" ? "已选择" : "选择创建"}</button><button className="btn sm" onClick={() => patch(item.id, { status: "ignored" })}><IconX size={13} />忽略</button></>}</div></article>)}</div>{selected.length > 0 && <div className="meeting-create"><span>已选择 {selected.length} 项</span><button className="btn primary" onClick={makePreview}><IconSend size={15} />预览创建钉钉待办</button></div>}</>}</section></div>
    {preview && <div className="meeting-confirm"><section className="panel"><h3>确认创建钉钉待办</h3><p>以下 {preview.items.length} 条事项将写入钉钉，创建后会立即回读验证。</p>{preview.items.map((item) => <div key={item.id}>{item.title} · {item.assignee_name || item.assignee_id} · {item.due_date || "未设截止日"}</div>)}<footer><button className="btn" onClick={() => setPreview(null)}>取消</button><button className="btn primary" disabled={busy} onClick={confirm}>确认创建</button></footer></section></div>}
  </div>;
}
