import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { IconAlertTriangle, IconInfoCircle, IconListCheck, IconMail, IconRefresh, IconShieldCheck, IconUsers } from "@tabler/icons-react";
import { api, todayStr, workbenchApi } from "../api.js";
import DateNav from "../components/DateNav.jsx";
import MeetingSchedule from "../components/MeetingSchedule.jsx";
import "./Overview2Page.css";

const WEEK=["周日","周一","周二","周三","周四","周五","周六"];
function fmtDateCn(iso){const [y,m,d]=iso.split("-").map(Number);return `${y}年${m}月${d}日 ${WEEK[new Date(y,m-1,d).getDay()]}`}
function greeting(){const h=new Date().getHours();return h<11?"早上好":h<14?"中午好":h<18?"下午好":"晚上好"}
function Kpi({label,icon,num,sub,subTone="muted",hint}){return <section className="oc-kpi"><div className="oc-kpi__top"><span className="oc-kpi__label">{label}{hint&&<span className="oc-kpi__hint"><button type="button" aria-label="查看统计规则"><IconInfoCircle size={14}/></button><span>{hint}</span></span>}</span><span className="oc-kpi__ic">{icon}</span></div><div className="oc-kpi__num">{num}</div><div className="oc-kpi__sub"><span className={`oc-dot oc-dot--${subTone}`}/>{sub}</div></section>}
function SuggestionBand({date,data}){const [text,setText]=useState("");const [loading,setLoading]=useState(false);const load=async(force=false)=>{setLoading(true);try{const r=await api.get(`/overview/suggestion?date=${date}${force?"&force=1":""}`);setText(r.suggestion)}finally{setLoading(false)}};useEffect(()=>{load()},[date,data.inputHash]);return <section className="oc-ai"><div className="oc-ai__head"><div className="oc-ai__titlewrap"><span className="oc-ai__spark">AI</span><span className="oc-ai__title">所选日期工作建议</span></div><button className="oc-ai__regen" onClick={()=>load(true)} disabled={loading} aria-label="重新生成建议"><IconRefresh size={15} className={loading?"oc-spin":""}/></button></div><p className="oc-ai__body">{loading?"正在基于当前注意事项生成…":text||"暂无建议"}</p><div className="oc-ai__tags">{data.attention.slice(0,3).map((item)=><span className="oc-chip" key={item.id}><span className={`oc-chip__priority oc-chip__priority--${(item.priority || "P2").toLowerCase()}`}>{item.priority}</span> · {item.title}</span>)}</div></section>}

export default function Overview2Page(){
 const [date,setDate]=useState(todayStr());const [data,setData]=useState(null);const [error,setError]=useState("");const [syncing,setSyncing]=useState(false);const nav=useNavigate();
 const load=()=>workbenchApi.dashboard(date).then(setData).catch((e)=>setError(e.message));useEffect(()=>{load()},[date]);
 const sync=async()=>{setSyncing(true);setError("");try{await workbenchApi.syncRun(date);await load()}catch(e){setError(e.message)}finally{setSyncing(false)}};
 if(!data&&!error)return <div className="spinner">加载中…</div>; if(!data)return <div className="error">加载失败：{error}</div>;
 const m=data.metrics;const latest=data.freshness.map((x)=>x.lastSuccessAt).filter(Boolean).sort().at(-1);const risks=data.projects.filter((p)=>["at_risk","overdue"].includes(p.status));const todoItems=data.attention.filter((x)=>x.kind==="todo");const mailItems=data.attention.filter((x)=>x.kind==="email");
 return <div className="oc"><header className="oc-header"><div className="oc-header__left"><div className="oc-greet">{greeting()}{data.displayName?`，${data.displayName}`:""}</div><div className="oc-date">{fmtDateCn(data.date)} · 团队态势一览</div></div><div className="oc-actions"><DateNav date={date} onChange={setDate}/><span className="oc-syncchip"><span className="oc-syncdot"/>{latest?`最近成功 ${new Date(latest).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`:"尚未同步"}</span><button className="oc-btn" onClick={sync} disabled={syncing}><IconRefresh size={15} className={syncing?"oc-spin":""}/>{syncing?"同步中…":"同步外部数据"}</button></div></header>
 {error&&<div className="error">{error}</div>}{!data.hasData&&<div className="oc-empty">所选日期暂无数据。{data.availableDateHint&&<>最近有数据日期：<button className="oc-card__link" onClick={()=>setDate(data.availableDateHint)}>{data.availableDateHint}</button></>}</div>}
 <div className="oc-kpis"><Kpi label="项目健康度" icon={<IconShieldCheck size={18}/>} num={m.projects.total?`${Math.round(m.projects.healthy/m.projects.total*100)}%`:"—"} sub={m.projects.total?`${m.projects.healthy} 健康 · ${m.projects.risk} 风险`:"暂无项目数据"} subTone={m.projects.risk?"warn":"ok"}/><Kpi label="待处理邮件" icon={<IconMail size={18}/>} num={m.email.open} sub={`${m.email.p0} 封 P0`} subTone={m.email.p0?"danger":"muted"}/><Kpi label="团队提交率" hint={`${m.team.ruleLabel || "按所选日期统计"}。当前统计日期：${m.team.metricDate || date}。手动切换日期后按所选日期统计。`} icon={<IconUsers size={18}/>} num={m.team.rate==null?"—":`${m.team.rate}%`} sub={`${m.team.submitted}/${m.team.rosterTotal} · 缺交 ${m.team.missing} 人`} subTone={m.team.missing?"warn":"ok"}/><Kpi label="待办完成率" icon={<IconListCheck size={18}/>} num={m.todos.rate==null?"—":`${m.todos.rate}%`} sub={`${m.todos.done}/${m.todos.total} 已完成`}/></div>
 <SuggestionBand date={date} data={data}/><div className="oc-grid"><div className="oc-col"><section className="oc-card oc-meeting-card"><div className="oc-card__head"><span className="oc-card__title">今日会议（{data.meetings.length}）</span><button className="oc-card__link" onClick={()=>nav("/calendar")}>查看日历 →</button></div><MeetingSchedule meetings={data.meetings} live={date===todayStr()}/></section><section className="oc-card"><div className="oc-card__head"><span className="oc-card__title">待处理邮件</span><button className="oc-card__link" onClick={()=>nav("/actions?tab=email")}>进入行动中心 →</button></div>{mailItems.slice(0,5).map((x)=><button className="oc-row" key={x.id} onClick={()=>nav("/actions?tab=email")}><span className={`oc-tag oc-tag--${x.priority.toLowerCase()}`}>{x.priority}</span><span className="oc-row__main"><span className="oc-row__title">{x.title}</span><span className="oc-row__sub">{x.detail}</span></span></button>)}{!mailItems.length&&<div className="oc-empty"><IconMail size={20}/>无待处理邮件</div>}</section></div>
 <div className="oc-col"><section className="oc-card"><div className="oc-card__head"><span className="oc-card__title">风险雷达</span><button className="oc-card__link" onClick={()=>nav("/projects")}>全部项目 →</button></div>{risks.map((p)=><div className="oc-risk-row" key={p.id}><span className="oc-risk-dot"/><div className="oc-risk-main"><div className="oc-risk-name">{p.name}</div><div className="oc-risk-sub">{p.owner||"未设置负责人"} · {p.progress}%</div></div><span className="oc-risk-status">{p.statusLabel}</span></div>)}{!data.projects.length?<div className="oc-empty"><IconAlertTriangle size={20}/>暂无项目数据</div>:!risks.length&&<div className="oc-empty">当前项目无风险信号</div>}</section><section className="oc-card"><div className="oc-card__head"><span className="oc-card__title">团队信号</span><button className="oc-card__link" onClick={()=>nav("/team")}>查看团队 →</button></div><div className="oc-signals"><div className="oc-signal"><span className="oc-signal__num">{data.pulse.blockers.length}</span><span className="oc-signal__lab">阻塞</span></div><div className="oc-signal"><span className="oc-signal__num">{data.pulse.reviewRequests.length}</span><span className="oc-signal__lab">待决策</span></div><div className="oc-signal"><span className="oc-signal__num">{data.pulse.missing.length}</span><span className="oc-signal__lab">未提交</span></div></div></section><section className="oc-card"><div className="oc-card__head"><span className="oc-card__title">最高优先级待办</span><button className="oc-card__link" onClick={()=>nav("/actions?tab=tasks")}>去处理 →</button></div>{todoItems.slice(0,5).map((x)=><div className="oc-todo-row" key={x.id}><span className={`oc-tag oc-tag--${x.priority.toLowerCase()}`}>{x.priority}</span><span className="oc-todo-txt">{x.title}</span></div>)}{!todoItems.length&&<div className="oc-empty">暂无待办</div>}</section></div></div></div>;
}
